#!/bin/bash -e

SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=${SCRIPT%/*}      
source $SCRIPTDIR/util.sh

HELP="
Run in directory with 'data.sh'.
Prints all <var> files for \$caselist or 'caselist.txt'.

Usage:

    $SCRIPT <var> [caselist.txt]

"

[[ $# -lt 1 || $# -gt 2 || $1 == "-h" || $1 == "--help" ]] && usage 1
[ -f ./data.sh ] || { echo "Run in directory with 'data.sh'"; usage 1; }

source ./data.sh
[ -n "${!1}" ] || { echo "Set '$1' in data.sh"; exit 1; }
[[ -n "$2" || -n "$caselist" ]] || { echo "Set 'caselist' in data.sh, or give [caselis.txt] argument"; usage 1; }

cases=$caselist
if [ -n "$2" ]; then
    cases=$(cat "$2") || { echo "Failed to read '$2'"; usage 1; }
fi

for case in $cases; do
    source ./data.sh
    printf "%s\n" ${!1}
done
