#!/bin/bash -e

SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=${SCRIPT%/*}      
source $SCRIPTDIR/util.sh

HELP="Prints all <var> file paths. 

$standard_var_help

Usage:

${0##*/} [-f caselist.txt] <var> [case1 case2 ... caseN]

-f caselist.txt         Uses case id's from caselist.txt
[case1 case2 ..caseN]   Use these case id's instead of a caselist file
"

# flags
while getopts "hf:" flag; do
    case "$flag" in
        h) usage 1;;
        f) caselist=$OPTARG;;
    esac
done
shift $((OPTIND-1))

# get positional arguments
IFS=" " read var cases <<<"$@"
[ -n "${var-}" ] || { echo -e "Specify variable <var>\n"; usage 1; }

# check input is ok
checkset_SetUpData $var
checkset_cases

for case in $cases; do
    source "$SetUpData"
    printf "%s\n" ${!var}
done
