#!/bin/bash -e

SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=${SCRIPT%/*}      
source $SCRIPTDIR/util.sh

HELP="
Run in directory with 'data.sh'.
Prints all <var> files for $caselist.

Usage:

    $SCRIPT <var>

"

[[ $# -lt 1 || $1 == "-h" || $1 == "--help" ]] && usage 1
[ -f ./data.sh ] || { echo "Run in directory with 'data.sh'"; usage 1; }

case='*' && source ./data.sh
[ -n "${!1}" ] || { echo "Set '$1' in data.sh"; exit 1; }
[ -n "$caselist" ] || { echo "Set 'caselist' in data.sh"; exit 1; }

for case in $caselist; do
    source ./data.sh
    printf "%s\n" ${!1}
done
