#!/bin/bash -e

SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=${SCRIPT%/*}      
source $SCRIPTDIR/util.sh

HELP="
${0##*/}: Prints all <var> filepaths that exist for a given set of cases.

$queryscript_helpmsg"

queryscript_parseargs "$@"

if $selectcases; then # doesn't work on remote file paths
    case_if_exists() {
        local case=$1
        source $SetUpData
        [ ! -e "${!var}" ] || echo $case
    }
    map "case_if_exists" $cases
else
    mypred() { test -e "$1" -o -L "$1"; }
    filter "mypred" $($SCRIPTDIR/all $var $cases)
fi
