#!/bin/bash -eu

# Check ./data.sh exists and source it
[ ! -f "$PWD/data.sh" ] && { echo "Run in directory with 'data.sh'"; exit 1; }
case='*' && source "$PWD/data.sh"

# Check caselist and status_vars set
[[ -n ${status_vars-} ]] || { echo "First set 'status_vars' variable in 'data.sh'"; exit 1; }
[[ -n ${caselist-} ]] || { echo "First set 'caselist' variable in 'data.sh'"; exit 1; }

# Check that each status variable is set
for var in $status_vars; do
    [[ -n ${!var-} ]] || { echo "Set '$var' in 'data.sh'"; exit 1; }
done

# if logfile doesn't exist, create it with header
logfile="./statuslog.csv"
if [ ! -f "$logfile" ]; then
    header="datetime,"
    for var in $status_vars; do
        header="$header,$var"
    done
    echo -e "$header,total" > "$logfile"
fi

# add status row
row="'$(date +"%Y-%m-%d %H:%M")'"
for var in $status_vars; do
    row="$row,$(status $var | cut -d"/" -f1)"
    total=$(status $var | cut -d"/" -f2)
done
echo -e "$row,$total" >> "$logfile"
cat "$logfile" | column -t -s","
