#!/bin/bash -eu

SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=${SCRIPT%/*}      
source $SCRIPTDIR/util.sh


case=000 && setupvars status_vars
logfile="./statuslog.csv"

# Make header
header="datetime"
for var in $status_vars; do
    header="$header,$var"
done
header="$header,total"

# Make row
row="'$(date +"%Y-%m-%d %H:%M")'"
for var in $status_vars; do
    row="$row,$(status $var | cut -d"/" -f1)"
    total=$(status $var | cut -d"/" -f2)
done
row="$row,$total"

# Add to log file
echo -e "$header" >> "$logfile"
echo -e "$row" >> "$logfile"

# Print
cat "$logfile" | column -t -s","
