#!/bin/bash

SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=${SCRIPT%/*}      
source $SCRIPTDIR/util.sh

HELP="
Run in directory with 'data.sh'.
Prints all <var> files that don't exist for \$caselist or 'caselist.txt'.

Usage:

    ${0##*/} <var> [caselist.txt]

"

# check args and ./data.sh
[[ $# -lt 1 || $# -gt 2 || $1 == "-h" || $1 == "--help" ]] && usage 1
[ -f ./data.sh ] || { echo "Run in directory with 'data.sh'"; usage 1; }
var=$1

# check var is set
source ./data.sh
[ -n "${!var}" ] || { echo "Set '$1' in data.sh"; exit 1; }
[[ -n "$2" ||  -n "$caselist" ]] || { echo "Set 'caselist' in data.sh" or supply [caselist.txt]; usage 1; }

pred="! -e"
filter "$pred" $($SCRIPTDIR/all $var $2)
