#!/bin/bash -e

source util.sh

HELP="
Run in directory with 'data.sh'.
Prints all <var> files that don't exist for \$caselist.

Usage:

    $SCRIPT_NAME <var>

"

[[ $# -lt 1 || $1 == "-h" || $1 == "--help" ]] && usage 1
[ -f ./data.sh ] || { echo "Run in directory with 'data.sh'"; usage 1; }

source ./data.sh
[ -n "${!1}" ] || { echo "Set '$1' in data.sh"; exit 1; }
[ -n "$caselist" ] || { echo "Set 'caselist' in data.sh"; exit 1; }

for c in $caselist; do
    case=$c && source ./data.sh
    [ ! -e ${!1} ] && printf "%s " ${!1}
done
