#!/bin/bash -e

SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=${SCRIPT%/*}      
source $SCRIPTDIR/util.sh

HELP="Run in directory with 'SetUpData.sh' or with environment variable
DATADIR set to path containing one.  Prints all <var> files that don't exist
for \$caselist, 'caselist.txt', or [case1 case2 .. caseN].  Usage:

${0##*/} [-c] [-f caselist.txt] <var>  [case1 case2 .. caseN]

-c                      Prints case id's, not file paths
-f caselist.txt         Uses case id's from caselist.txt
[case1 case2 ..caseN]   Use these case id's instead of a caselist file
"

# flags
printcases=false
while getopts "hcf:" flag; do
    case "$flag" in
        h) usage 1;;
        c) printcases=true;;
        f) caselist=$OPTARG;;
    esac
done
shift $((OPTIND-1))

# get positional arguments
IFS=" " read var cases <<<"$@"
[ -n "${var-}" ] || { echo -e "Specify variable <var>.\n"; usage 1; }

# check input is ok
checkset_SetUpData $var
checkset_cases

if $printcases; then
    case_if_not_exists() {
        local case=$1
        source $SetUpData
        [ -e "${!var}" ] || echo $case
    }
    map "case_if_not_exists" $cases
else
    pred="! -e"
    filter "$pred" $($SCRIPTDIR/all $var $cases)
fi
