#!/bin/bash -eu

usage() {
    echo -e "\
Saves a slice of an image and its labelmap to see if they
are aligned correctly (in pixel space).

Usage:

    ${0##/} [-a <axis>] [-s \"<sz0..>\"] <img> <labelmap> <out.png>
"
}

axis=2
while getopts "ha:s:" flag; do
    case "$flag" in
        h) usage 1;;
        a) axis=$OPTARG;;
        s) scale=$OPTARG;;
    esac
done
shift $((OPTIND-1))

[[ $# -ne 3 || $1 == "-h*" ]] && { usage; exit 1; }
img=$1
lbl=$2
out=$3

tmp=$(mktemp -d)
img2d="$tmp/img.nrrd"
lbl2d="$tmp/lbl.nrrd"
# if it's a dwi, collapse it into a 3d volume first
if unu head $img | grep -q 'dimension: 4'; then  
    img3d="$tmp/img3d.nrrd"
    #unu project -a 3 -m mean -i $img -o $img3d
    unu slice -a 3 -p 0 -i $img -o $img3d
    img=$img3d
    unu project -a $axis -m mean -i $img | unu heq -b 30000 -a 0.8 | unu gamma -g 1.8 -o $img2d
else
    unu project -a $axis -m mean -i $img | unu heq -b 30000 -a 0.8 | unu gamma -g 1.3 -o $img2d
fi
unu project -a $axis -m max -i $lbl | unu 3op ifelse - 2 1 -o $lbl2d
if [ -n "${scale-}" ]; then
    unu 2op x $img2d $lbl2d | unu resample -s $scale | unu quantize -b 8 -o $3
else
    unu 2op x $img2d $lbl2d | unu quantize -b 8 -o $3
fi
