#!/bin/bash -eu

usage() {
echo -e "
Only works on nrrds for now.  If you need it for nifti, 
email Ryan (reckbo@bwh.harvard.edu).

    ${0##*/} <nrrd>

"
}

[ $# -eq 1 ] && [[ $1 != "-h" ]] || { usage; exit 1; }
[ -f $1 ] || { echo "'$1' doesn't exist"; exit 1; }

[[ $1 == *nrrd ]] || { echo "Only works on .nrrd's for now"; exit 1; }

if [[ $1 == *qcfail.nrrd ]]; then
    out=$1
    echo "Failed QC previously, not renaming"
elif [[ $1 == *qc.nrrd ]]; then
    out=${1/qc.nrrd/qcfail.nrrd}
    echo "Passed QC previously, renaming to '$out'"
    mv $1 $out
else
    out=${1/nrrd/qcfail\.nrrd}
    echo "Not QC'ed yet, renaming to '$out'"
    mv $1 $out
fi

sed -i "2i# QC'ed (FAIL) by $(whoami) on $(date)" $out

echo "Made '$out' and stamped it's header (view it by running 'unu head $out')"
