#!/usr/bin/env bash

set -eu

SCRIPT=$(readlink -m $(type -p $0))
SCRIPT_DIR=$(dirname ${SCRIPT})      
source "$SCRIPT_DIR/util.sh"

HELP_TEXT="
Compute a rigid registration transformation using ANTS.

Usage:
    $(basename $0) [-f |--fast] <moving> <fixed> [outrigid]

where <moving> and <fixed> are 3D images. [-f | --fast] is mainly
for debugging.
"

DOFAST=""
if [[ -n ${1-} ]]; then
    [[  $1 == "-h" || $1 == "--help" ]] && usage 0
    [[  $1 == "-f" || $1 == "--fast" ]] && { DOFAST="--number-of-affine-iterations 1"; shift; }
fi
[ $# -lt 3 ] && usage 1

moving=$1; fixed=$2; outrigid=${3:-$(base $moving)_in_$(base $fixed)-rigid.txt}
check_vars ANTSPATH

log "Compute the rigid registration from '$moving' to '$fixed' to make '$outrigid'"
tmp=$(mktemp -d) && pre=$tmp/$(base $outrigid)
run ${ANTSPATH}/ANTS 3 -m MI[$fixed,$moving,1,32] -i 0 -o $pre --do-rigid $DOFAST
# from antsaffine.sh:
#RIGID="--rigid-affine true  --affine-gradient-descent-option  0.5x0.95x1.e-4x1.e-4"
#run $(antspath ANTS) 3 -m MI[${fixed},${moving},1,32] -o ${pre} -i 0 --use-Histogram-Matching --number-of-affine-iterations 10000x10000x10000x10000x10000 $RIGID
mv ${pre}Affine.txt "$outrigid"
rm -rf "$tmp"
log_success "Made rigid transform '$outrigid'"
