#!/bin/bash -e

source util.sh

HELP="
Prints progress for <var>.
Run in directory with 'data.sh' that sets <var> file path
and 'caselist'.

Usage:

    $SCRIPT <var>

"

# check args and ./data.sh
[[ $# -lt 1 || $1 == "-h" || $1 == "--help" ]] && usage 1
[ -f ./data.sh ] || { echo "Run in directory with 'data.sh'"; usage 1; }
var=$1

# check var is set
source ./data.sh
[ -n "${!var}" ] || { echo "Set '$var' in data.sh"; exit 1; }
[ -n "$caselist" ] || { echo "Set 'caselist' in data.sh"; exit 1; }

# if var is remote 
if [[ ${!var} == *:* ]]; then
    IFS=":" read -r server remotepath <<<"${!var}"
    files=$(all $var $caselist)
    num_exist=$(ssh $server "for i in $files; do [ -e "\$i" ] && echo \$i; done | wc -l")
    printf "%s/%s\n" $num_exist $(echo $caselist | wc -w)
    exit 0
fi

# local
files=$(all $var $caselist)
num_exist=$(for i in $files; do [ -e "$i" ] && echo $i; done | wc -l)
echo $num_exist/$(echo $caselist | wc -w)
