#!/bin/bash -e

source util.sh

HELP="
Run in directory with 'data.sh'.

Usage:

    $SCRIPT <var>

"

[[ $# -lt 1 || $1 == "-h" || $1 == "--help" ]] && usage 1
[ -f ./data.sh ] || { echo "Run in directory with 'data.sh'"; usage 1; }
case='*' && source ./data.sh
var="$1"
[ -n "${!var}" ] || { echo "Set '$var' in data.sh"; exit 1; }
[ -n "$caselist" ] || { echo "Set 'caselist' in data.sh"; exit 1; }
printf "%s/%s\n" $(echo ${!var} | wc -w) $(echo $caselist | wc -w)
