#!/bin/bash -eu

SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=${SCRIPT%/*}      
source $SCRIPTDIR/util.sh

usage() {
    echo -e "\
Lists variables defined in './SetUpData.sh ./dataEnv.sh' or
'/path/to/data/SetUpData.sh'

Usage:
    ${0##*/} 
    ${0##*/} path/to/data/

e.g. 
    ${0##*/} 
    ${0##*/} \$intrust
    ${0##*/} \$szes
    ${0##*/} \$nfl
"
}

data="./SetUpData.sh ./dataEnv.sh"
[[ ${1-} == "-h" || ${1-} == "--help" ]] && { usage; exit 1; }
if [ -n "${1-}" ]; then
    data="$1/SetUpData.sh $1/dataEnv.sh"
fi

out=$(cat $data 2>/dev/null || true)
[ -n "$out" ] || { echo "No output from '$data.sh', do they exist?"; usage; exit 1; }

echo -e "$out" | grep "=" | column -s"=" -t
