#!/bin/bash -eu

SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=${SCRIPT%/*}      
source $SCRIPTDIR/util.sh

HELP="\
Prints all <var> file paths. 
Run in directory with 'SetUpData.sh' that has '<var>=/path/to/\$case-file'
defined in it.  The set of cases must either be defined in SetUpData.sh (e.g.
as caselist=mycaselist.txt or cases=\"case1 case2.. caseN\"), or on the
commandline (see below).

Usage:
    ${0##*/} [-c] [-d delimiter] [-l \"case1 case2 ..\"] [-f mycaselist.txt] <var1> <var2> ... <varN>

-c                      Prints case id's along with file paths (this differs from 'completed' and 'missing' scripts)
-f <caselist>           Uses case id's from <caselist> (one per line, but can include comments)
-l case1 case2 ..caseN  Use these case id's instead of a caselist file

Examples:
    all -c t1  # Prints caseids and t1 paths
    all -d\" \" t1 t2  # print t1 and t2 paths separated by a space
"

source $SCRIPTDIR/queryscript.sh

for case in $cases; do
    source "SetUpData.sh"
    output=()
    if $printcaseids; then
        output+=$case
    fi
    for var in $vars; do
        output+=("${!var}")
    done
    join "$delim" ${output[@]}
done
