#!/bin/bash -eu

SCRIPT=$(readlink -m $(type -p "$0"))
SCRIPTDIR=${SCRIPT%/*}      

descrip="measurement frame"
filtfunc() {
    printf "$1" | grep "measurement frame:" | sed 's/smeasurement frame: //'
}

source "$SCRIPTDIR"/nrrdinfo.sh
