#!/bin/bash -eu

SCRIPT=$(readlink -m $(type -p "$0"))
SCRIPTDIR=${SCRIPT%/*}      

descrip="space origins"
filtfunc() {
    printf "$1" | grep "origin" | sed 's/space origin: //'
}

source "$SCRIPTDIR"/nrrdinfo.sh
