#!/bin/bash -eu

SCRIPT=$(readlink -m $(type -p "$0"))
SCRIPTDIR=${SCRIPT%/*}      

descrip="space"
filtfunc() {
    printf "$1" | grep "space:" | sed 's/space: //'
}

source "$SCRIPTDIR"/nrrdinfo.sh
