#!/bin/bash -e

SCRIPT=$(readlink -m $(type -p "$0"))
SCRIPTDIR=${SCRIPT%/*}      

descrip="space directions"
filtfunc() {
    printf "$1" | grep "space direction" | sed 's/space directions: //'
}

source "$SCRIPTDIR"/nrrdinfo.sh
