#!/usr/bin/env bash
set -e

SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=${SCRIPT%/*}
source $SCRIPTDIR/util.sh

HELP="Prints progress ('done/total') for <var>.
$standard_var_help
Usage:

    ${0##*/} <var>
"

# check args and ./SetUpData.sh
[[ $# -lt 1 || $1 == "-h" || $1 == "--help" ]] && usage 1
var=$1

case=000 && setupvars "$var"  # set dummy case just to check if var is a valid variable
setupcases
echo $($SCRIPTDIR/completed $var | wc -l)/$(echo $cases | wc -w)
