#!/bin/bash -eu

SCRIPT=$(readlink -m $(type -p "$0"))
SCRIPTDIR="${SCRIPT%/*}"

usage() {
    echo -e "

    ${0##*/} <tract1.vtk> <tract2.vtk> ... <tractN.vtk>

    'whitematteranalysis/bin' needs to be on your path. Alternatively, you can
    set its path in $SCRIPTDIR/config.sh.  You can also set 'slicer' to point
    to your 'Slicer' excecutable you would like to use.  Otherwise, the default
    is just 'Slicer'.
    " 
}

[ $# -gt 0 ] || { usage; exit 1; }

# default Slicer
slicer=Slicer
sliceropts="--disable-cli-modules --disable-scripted-loadable-modules" 

# source config file that may set 'slicer' and add path to whitematteranalyis 
if [ -e "$SCRIPTDIR/config.sh" ]; then
    source "$SCRIPTDIR/config.sh"  # can set slicer here
fi

# check that slicer executable exists
[ -f "$(readlink -m $(type -p "$slicer"))" ] || { echo "Can't find slicer: '$slicer'"; usage; exit 1; }

# make temporary directory with symlinks
dirTmp=$(mktemp -d)
ln -s "$@" $dirTmp

# make mrml file
wm_create_mrml_file.py "$dirTmp"

# load in Slicer
export PYTHONPATH=
export LD_LIBRARY_PATH=
"$slicer" "$sliceropts" "$dirTmp"/scene.mrml

